### ISSUE TITLE
Compiling from source code does not work

### ISSUE THREAD

**Issue by EDLLT** [ProtonVPN/proton-vpn-browser-extension#9]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Environment: Ubuntu 24.04.01 x86_64

I tried building for Chrome which had resulted in a multitude of errors

```
edllt@HP:~/src/proton-vpn-browser-extension$ npm run build
build
webpack --mode=production
ERROR in ./source/js/api.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /home/edllt/src/proton-vpn-browser-extension/source/js/api.ts.
at makeSourceMapAndFinish (/home/edllt/src/proton-vpn-browser-extension/node_modules/ts-loader/dist/index.js:52:18)
at successLoader (/home/edllt/src/proton-vpn-browser-extension/node_modules/ts-loader/dist/index.js:39:5)
at Object.loader (/home/edllt/src/proton-vpn-browser-extension/node_modules/ts-loader/dist/index.js:22:5)
@ ./source/js/account/fork/requestFork.ts 39:0-46 54:32-49
@ ./source/js/account/openForkTab.ts 37:0-49 53:37-48
@ ./source/js/onboarding.ts 37:0-52 76:47-58 81:41-52
ERROR in ./source/js/popup.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /home/edllt/src/proton-vpn-browser-extension/source/js/popup.ts.
at makeSourceMapAndFinish (/home/edllt/src/proton-vpn-browser-extension/node_modules/ts-loader/dist/index.js:52:18)
at successLoader (/home/edllt/src/proton-vpn-browser-extension/node_modules/ts-loader/dist/index.js:39:5)
at Object.loader (/home/edllt/src/proton-vpn-browser-extension/node_modules/ts-loader/dist/index.js:22:5)
ERROR in /home/edllt/src/proton-vpn-browser-extension/source/js/api.ts
./source/js/api.ts 7:37-49
[tsl] ERROR in /home/edllt/src/proton-vpn-browser-extension/source/js/api.ts(7,38)
TS2307: Cannot find module './tools/ip' or its corresponding type declarations.
@ ./source/js/account/fork/requestFork.ts 39:0-46 54:32-49
@ ./source/js/account/openForkTab.ts 37:0-49 53:37-48
@ ./source/js/onboarding.ts 37:0-52 76:47-58 81:41-52
ERROR in /home/edllt/src/proton-vpn-browser-extension/source/js/popup.ts
./source/js/popup.ts 86:26-49
[tsl] ERROR in /home/edllt/src/proton-vpn-browser-extension/source/js/popup.ts(86,27)
TS2307: Cannot find module './account/requireUser' or its corresponding type declarations.
webpack compiled with 4 errors
```

I then checked out to an older version which compiled successfully

**Comment by kylekatarnls** [comment]
Sorry for the inconvenience, I just pushed the missed files, can you retry?
